import { expect, test } from "@playwright/test";

test.beforeAll(async({request})=>{const response=await request.post("/api/dev",{data:{action:"seed",value:"demo"}});expect(response.ok()).toBe(true)});

test("open, accelerate, settle, and see the career result",async({page})=>{await page.goto("/terminal?tokenId=7");await page.getByRole("button",{name:/BTC/}).click();await page.getByRole("button",{name:"LONG"}).click();await page.getByRole("button",{name:/NORMAL/}).click();await page.getByTestId("open-session").click();await expect(page.getByText("SESSION LOCKED // LIVE WITH IT")).toBeVisible();await page.getByTestId("finish-session").click();await expect(page).toHaveURL(/\/share\//);await expect(page.getByText(/CAREER PNL/)).toBeVisible()});
test("a second session is blocked by the locked terminal",async({page})=>{await page.goto("/terminal?tokenId=42");await page.getByTestId("open-session").click();await expect(page.getByText("SESSION LOCKED // LIVE WITH IT")).toBeVisible();await expect(page.getByTestId("open-session")).toHaveCount(0)});
test("FULL SEND crash liquidates exactly once",async({page})=>{await page.request.post("/api/dev",{data:{action:"seed",value:"fresh"}});await page.request.post("/api/dev",{data:{action:"align-crash"}});await page.request.post("/api/dev",{data:{action:"scenario",value:"CRASH"}});await page.goto("/terminal?tokenId=7");await page.getByRole("button",{name:/FULL SEND/}).click();await page.getByRole("button",{name:"4H"}).click();await page.getByTestId("open-session").click();await page.getByTestId("finish-session").click();await expect(page.getByText(/LIQUIDATED/).first()).toBeVisible();await page.goto("/freaks/7");await expect(page.getByText("0 / 1 / 1")).toBeVisible()});
test("profile exposes history and equity chart",async({page})=>{await page.goto("/freaks/1337");await expect(page.getByText("EQUITY CURVE")).toBeVisible();await expect(page.getByText("RECENT SESSIONS")).toBeVisible()});
test("leaderboard renders both career and skill rankings",async({page})=>{await page.goto("/leaderboard");await expect(page.getByText("CAREER PNL",{exact:true})).toBeVisible();await expect(page.getByText("TRADER RATING",{exact:true})).toBeVisible()});
test("development art lab separates Genesis and zero-fallback production-only QA",async({page})=>{await page.goto("/art-lab");await expect(page.getByRole("heading",{name:"ART LAB"})).toBeVisible();await expect(page.getByRole("heading",{name:"PRODUCTION PACK V1"})).toBeVisible();await expect(page.getByTestId("production-pack-preview")).toHaveCount(6);await expect(page.getByRole("heading",{name:"MINI COLLECTION V1"})).toBeVisible();await expect(page.getByTestId("mini-collection-card")).toHaveCount(50);expect(await page.getByTestId("mini-collection-card").first().locator('[data-asset-source="IMAGE"]').count()).toBeGreaterThanOrEqual(5);await expect(page.getByTestId("mini-qa-report")).toContainText("MISSING IMAGE0");const first=page.getByTestId("mini-collection-card").first();await first.getByText("QA METADATA").click();await expect(first.getByText("CANONICAL RENDER SIGNATURE")).toBeVisible();await first.getByLabel(/Flag MINI COLLECTION V1/).selectOption("STRONG");await expect(first.getByTestId("mini-collection-card-problem-flag")).toHaveText("STRONG");await first.getByLabel(/Flag MINI COLLECTION V1/).selectOption("");await expect(first.getByTestId("mini-collection-card-problem-flag")).toHaveCount(0);await page.getByLabel("MINI CAREER").selectOption("WHALE");await expect(page.getByTestId("mini-collection-card")).toHaveCount(8);await page.getByLabel("MINI CAREER").selectOption("ALL");await page.getByLabel("MINI SORT BY").selectOption("VISUAL_FINGERPRINT");await expect(page.getByTestId("mini-collection-card")).toHaveCount(50);await expect(page.getByRole("heading",{name:"PRODUCTION ONLY — 50 FREAKS"})).toBeVisible();await expect(page.getByTestId("production-only-card")).toHaveCount(50);await expect(page.getByTestId("production-only-card").first().locator('[data-asset-source="IMAGE"]')).toHaveCount(10);await expect(page.getByTestId("production-only-card").first()).toContainText("11 IMAGE · 0 SVG fallback");await expect(page.getByTestId("production-only-qa-report")).toContainText("SVG FALLBACK USES0");const productionFirst=page.getByTestId("production-only-card").first();await productionFirst.getByText("QA METADATA").click();await expect(productionFirst.getByText("VISUAL FINGERPRINT HASH")).toBeVisible();await expect(page.getByTestId("art-evolution")).toHaveCount(6);await expect(page.getByTestId("matrix-body")).toHaveCount(8);await expect(page.getByTestId("matrix-skin")).toHaveCount(8);await expect(page.getByTestId("matrix-head")).toHaveCount(10);await expect(page.getByTestId("matrix-eyes")).toHaveCount(10);await expect(page.getByTestId("matrix-mouth")).toHaveCount(8);await expect(page.getByTestId("matrix-hair")).toHaveCount(12);await page.getByRole("checkbox",{name:"DEBUG LABELS"}).check();await expect(page.getByText("PRODUCTION ASSET MODE").first()).toBeVisible();await expect(page.getByTestId("asset-mode").filter({hasText:"= IMAGE"}).first()).toBeVisible()});
