import { expect, test } from "@playwright/test";

test.beforeAll(async({request})=>{const response=await request.post("/api/dev",{data:{action:"seed",value:"demo"}});expect(response.ok()).toBe(true)});

test("open, accelerate, settle, and see the career result",async({page})=>{await page.goto("/terminal?tokenId=7");await page.getByRole("button",{name:/BTC/}).click();await page.getByRole("button",{name:"LONG"}).click();await page.getByRole("button",{name:/NORMAL/}).click();await page.getByTestId("open-session").click();await expect(page.getByText("SESSION LOCKED // LIVE WITH IT")).toBeVisible();await page.getByTestId("finish-session").click();await expect(page).toHaveURL(/\/share\//);await expect(page.getByText(/CAREER PNL/)).toBeVisible()});
test("a second session is blocked by the locked terminal",async({page})=>{await page.goto("/terminal?tokenId=42");await page.getByTestId("open-session").click();await expect(page.getByText("SESSION LOCKED // LIVE WITH IT")).toBeVisible();await expect(page.getByTestId("open-session")).toHaveCount(0)});
test("FULL SEND crash liquidates exactly once",async({page})=>{await page.request.post("/api/dev",{data:{action:"seed",value:"fresh"}});await page.request.post("/api/dev",{data:{action:"align-crash"}});await page.request.post("/api/dev",{data:{action:"scenario",value:"CRASH"}});await page.goto("/terminal?tokenId=7");await page.getByRole("button",{name:/FULL SEND/}).click();await page.getByRole("button",{name:"4H"}).click();await page.getByTestId("open-session").click();await page.getByTestId("finish-session").click();await expect(page.getByText(/LIQUIDATED/).first()).toBeVisible();await page.goto("/freaks/7");await expect(page.getByText("0 / 1 / 1")).toBeVisible()});
test("profile exposes history and equity chart",async({page})=>{await page.goto("/freaks/1337");await expect(page.getByText("EQUITY CURVE")).toBeVisible();await expect(page.getByText("RECENT SESSIONS")).toBeVisible()});
test("leaderboard renders both career and skill rankings",async({page})=>{await page.goto("/leaderboard");await expect(page.getByText("CAREER PNL",{exact:true})).toBeVisible();await expect(page.getByText("TRADER RATING",{exact:true})).toBeVisible()});
test("development art lab exposes preview, evolution, and full trait matrices",async({page})=>{await page.goto("/art-lab");await expect(page.getByRole("heading",{name:"ART LAB"})).toBeVisible();await expect(page.getByTestId("art-preview")).toHaveCount(50);await expect(page.getByTestId("art-evolution")).toHaveCount(6);await expect(page.getByTestId("matrix-body")).toHaveCount(8);await expect(page.getByTestId("matrix-skin")).toHaveCount(8);await expect(page.getByTestId("matrix-head")).toHaveCount(10);await expect(page.getByTestId("matrix-eyes")).toHaveCount(10);await expect(page.getByTestId("matrix-mouth")).toHaveCount(8);await expect(page.getByTestId("matrix-hair")).toHaveCount(12)});
